#! /usr/bin/env perl

use strict;

use Cwd qw(abs_path);
use File::Basename qw(dirname);

my $test_dir = dirname abs_path $0;

chdir $test_dir or die "cannot chdir to '$test_dir': $!";
system './run_epd.pl', 'epd/dm2.epd', 'sd 9' == 0 or exit 1;
