#! /usr/bin/env perl
	eval 'exec /usr/bin/perl -wS $0 ${1+"$@"}'
		if $running_under_some_shell;

use strict;

use Cwd qw(abs_path);
use File::Basename qw(basename dirname);

my $test_dir = dirname abs_path __FILE__;

my $epd_file = basename __FILE__;
$epd_file =~ s{^check_(.*)$}{epd/$1.epd};

chdir $test_dir or die "cannot chdir to '$test_dir': $!";
my $engine = '../lisco.exe';
$engine = '../lisco' if !-e $engine;
my $status = system './solve_epd.pl', $engine, $epd_file, 'sd 9';
exit 23 if $status != 0;