#! /usr/bin/env perl

use strict;

use Cwd qw(abs_path);
use File::Basename qw(basename dirname);

my $test_dir = dirname abs_path __FILE__;

my $epd_file = basename __FILE__;
$epd_file =~ s{^check_(.*)$}{epd/$1.epd};

chdir $test_dir or die "cannot chdir to '$test_dir': $!";
my $engine = '../lisco.exe';
$engine = '../lisco' if !-e $engine;
system './solve_epd.pl', $engine, $epd_file, 'sd 9' == 0 or exit 1;
